export const ipo = {
    default: {
        location_validation_phase: {
            heading: `DISCLAIMER`,
            content: `Due to applicable legal restrictions, access to this section of our website is restricted to users located in certain jurisdictions. Please confirm your location here`
        },
        disclaimer_us_consent_phase: {
            heading: `DISCLAIMER – IMPORTANT`,
            content: `<p><strong>IMPORTANT INFORMATION</strong></p>
         <p>You have indicated that you are located in the United States. These materials are not intended for, directed at or accessible by persons located in the United States. However, persons located in the United States that are able to make the certifications below may access these materials. Please read the certifications below carefully and tick the checkboxes if you can make the certifications. If you cannot make the certifications below, please choose “I DO NOT AGREE” below.</p>
         <p><strong><em>Certifications</em></strong></p>
         <p><strong>“We are a “qualified institutional buyer” (a “<em>QIB</em>”) as defined in Rule 144A under the U.S. Securities Act of 1933, as amended (the “<em>Securities Act</em>”). Further, if we are acting as a fiduciary or agent for one or more investor accounts, (a) each such account is a QIB, (b) we have investment discretion with respect to each account, and (c) we have full power and authority to make the representations, warranties, agreements and acknowledgements herein on behalf of each such account.”</strong></p>
         <p><input id="us_cert1" name="us_cert1" type="checkbox" value="US-certification1"><strong>“We acknowledge that the materials relate to a transaction that is not subject to, or is only available in the United States pursuant to an exemption from the registration requirements of the Securities Act.</strong> <strong>No U.S. federal or state securities commission or regulatory authority has approved or disapproved of the transaction or passed upon the adequacy or accuracy of the information on the following pages. Any representation to the contrary is a criminal offence in the United States.”</strong></p>
         <p><input id="us_cert2" name="us_cert2" type="checkbox" value="US-certification2">By clicking “I AGREE” below, you are confirming that the certifications made are accurate and that you would like to access the materials. You agree that the materials you receive are for your own use and will not be distributed to any person outside of your organization. You acknowledge that your data will be held by SCHOTT Pharma AG &amp; Co. KGaA and processed to ensure compliance with applicable regulations.</p>`
        },
        disclaimer_consent_phase: {
            heading: `DISCLAIMER – IMPORTANT`,
            content: `<p><strong>The following materials are not directed at or to be accessed by persons located in the United States (except for “qualified institutional buyers” within the meaning of the U.S. Securities Act of 1933, as amended (the “Securities Act”)), Canada, Australia or Japan or any jurisdictions in which the distribution or release would be unlawful. These materials do not constitute or form a part of any offer or solicitation to purchase or subscribe for securities in the United States, Australia, Canada or Japan or in any other jurisdiction in which such offer or solicitation is not authorized or to any person to whom it is unlawful to make such offer or solicitation.</strong></p>
            <p><strong>The shares mentioned herein have not been, and will not be, registered under the Securities Act and may not be offered or sold in the United States, except pursuant to an exemption from the registration requirements of the Securities Act. There will be no public offer of the shares in the United States.</strong></p>
            <p><strong><span class="text-underline">For users located in the United Kingdom</span></strong></p>
            <p><strong>In the United Kingdom the following materials are only directed at (i) investment professionals falling within Article 19(5) of the Financial Services and Markets Act 2000 (Financial Promotion) Order 2005, as amended (the “Order”) or (ii) high net worth companies, and other persons to whom it may lawfully be communicated, falling within Article 49(2)(a) to (d) of the Order, or (iii) persons to whom an invitation or inducement to engage in an investment activity (within the meaning of section 21 of the United Kingdom Financial Services and Markets Act 2000) in connection with the issue or sale of any securities may otherwise be lawfully communicated or caused to be communicated (all such persons together being referred to as “relevant persons”). The shares are only available to, and any invitation, offer or agreement to subscribe, purchase or otherwise acquire such shares will be engaged in only with, relevant persons. Any person who is not a relevant person should not act or rely on the materials or any of their contents.</strong></p>
            
            <p><strong><span class="text-underline">For users located within the European Economic Area (other than Germany)</span></strong></p>
            <p><strong>You are located or resident in a member state of the European Economic Area (“EEA”) and are a “qualified investor” within the meaning of Article 2(e) of Regulation (EU) 2017/1129 of the European Parliament and of the Council of 14 June 2017 on the prospectus to be published when securities are offered to the public or admitted to trading on a regulated market, and repealing Directive 2003/71/EC. Further, if you are acting as a fiduciary or agent for one or more investor accounts, (a) each such account is a qualified investor, (b) you have investment discretion with respect to each account, and (c) you have full power and authority to make the representations, warranties, agreements and acknowledgements herein on behalf of each such account.</strong></p>
            <p>Viewing the materials you seek to access may not be lawful in certain jurisdictions. In other jurisdictions, only certain categories of person may be allowed to view such materials. Any person who wishes to view these materials must first satisfy themselves that they are not subject to any local requirements that prohibit or restrict them from doing so.</p>
            <p>If you are not permitted to view materials on this webpage or are in any doubt as to whether you are permitted to view these materials, please exit this webpage.</p>
            <p><strong>Basis of access</strong></p>
            <p>Access to electronic versions of these materials is being made available on this webpage by [COMPANY AG] in good faith and for information purposes only. Making press announcements and other documents available in electronic format on this webpage does not constitute an offer to sell or the solicitation of an offer to buy shares in [COMPANY AG]. Furthermore, it does not constitute a recommendation by [COMPANY AG] or any other party to buy or sell shares in [COMPANY AG].</p>
            <p>You agree that the materials you receive are for your own use and that you will not distribute the materials to any other person.</p>
            <p>To the extent that any materials on this website contain forward-looking statements, such statements do not represent facts and are characterized by the words “will”, “expect”, “believe”, “estimate”, “intend”, “aim”, “assume” or similar expressions. Such statements express the intentions, opinions or current expectations and assumptions of [COMPANY AG] and are based on current plans, estimates and forecasts that [COMPANY AG] has made to the best of its knowledge, but which may not be correct in the future. Forward-looking statements are subject to risks and uncertainties that are difficult to predict and usually cannot be influenced. It should be kept in mind that the actual events or consequences may differ materially from those contained in or expressed by such forward-looking statements.</p>
            <p><strong>Confirmation of understanding and acceptance of disclaimer</strong></p>
            <p>By clicking on the “I CONFIRM” button, I certify that:</p>
            <ul>
				<li>I am not located in the United States (unless I am a “qualified institutional buyer,” as defined above), Canada, Australia or Japan or any jurisdictions in which the distribution or release would be unlawful;</li>
				<li>if I am located in the United Kingdom, I am a “relevant person” (as defined above); and</li>
				<li>if I am located in the European Economic Area (other than Germany), I am a “qualified investor” (as defined above)."</li>
            </ul>
            <p>I have read and understood the disclaimer set out above. I understand that it may affect my rights. I agree to be bound by its terms. By clicking on the “I CONFIRM” button, I confirm that I am permitted to proceed to electronic versions of these materials.</p>`
        },
        no_access_phase: {
            content: `<p>Due to applicable legal restrictions, electronic versions of these materials are not accessible by persons located in the jurisdictions you have indicated. Click <a href="/">here</a> to return to the homepage.</p>`
        }
    }
    /*DE: {
		location_validation_phase: {
			content: `Due to applicable legal restrictions, access to this section of our website is restricted to users located in certain jurisdictions. Please confirm your location here.`
		},
		disclaimer_consent_phase: {
			heading: `HAFTUNGSAUSSCHLUSS – WICHTIG`,
			content: `<p><strong>Die auf den folgenden Webseiten enthaltenen Unterlagen sind nicht an Personen gerichtet, die sich in den Vereinigten Staaten (es sei denn, sie sind „Qualified Institutional Buyers“ im Sinne des U.S. Securities Act von 1933, in der gültigen Fassung, (der “Securities Act”)), Kanada, Australien oder Japan oder einer Rechtsordnung, in welcher eine Verteilung oder Veröffentlichung rechtswidrig wäre, befinden, oder für deren Zugriff bestimmt. Diese Unterlagen begründen oder bilden weder in den Vereinigten Staaten, Australien, Kanada oder Japan oder einer Rechtsordnung, in welcher ein solches Angebot oder eine solche Werbung nicht gestattet sind, noch gegenüber einer Person, der gegenüber es rechtswidrig ist, ein solches Angebot abzugeben oder eine solche Aufforderung zu schalten, einen Teil eines Angebots oder eine Aufforderung dazu, Wertpapiere zu erwerben oder zu zeichnen.</strong></p>
            <p><strong>Die hier erwähnten Aktien wurden nicht und werden nicht gemäß dem Securities Act registriert werden und dürfen in den Vereinigten Staaten außer im Rahmen der Ausnahmetatbestände von den Registrierungsanforderungen des Securities Act nicht angeboten oder verkauft werden. In den Vereinigten Staaten wird es für die Aktien kein öffentliches Angebot geben.</strong></p>
            <p><strong><span class="text-underline">Für Benutzer, die sich im Vereinigten Königreich befinden</span></strong></p>
            <p><strong>Die nachfolgenden Unterlagen sind innerhalb des Vereinigten Königreiches nur an (i) professionelle Anleger, die unter Artikel 19(5) der Financial Services and Markets Act 2000 (Financial Promotion) Order 2005, in der jeweils gültigen Fassung, (die „Verordnung“) fallen, oder (ii) vermögende Gesellschaften und andere Personen, die unter Artikel 49(2)(a) bis (d) der Verordnung fallen und an die man rechtmäßig herantreten kann, verteilt werden und sind nur an sie gerichtet oder (iii) Personen denen eine Einladung oder Aufforderung zur Ausübung einer Investitionstätigkeit (im Sinne von Abschnitt 21 des Financial Services and Markets Act 2000) im Zusammenhang mit der Ausgabe oder dem Verkauf von Wertpapieren anderweitig rechtmäßig kommuniziert oder die Kommunikation veranlasst werden darf (wobei diese Personen zusammen als „relevante Personen“ bezeichnet werden). Die Aktien stehen nur relevanten Personen zur Verfügung und jede Aufforderung, jedes Angebot oder jede Vereinbarung, solche Aktien zu zeichnen, zu kaufen oder anderweitig zu erwerben, wird nur gegenüber relevanten Personen abgegeben. Personen, die keine relevanten Personen sind, sollten in keinem Fall im Hinblick oder im Vertrauen auf diese Unterlagen oder ihren Inhalt handeln.</strong></p>
            <p><strong><span class="text-underline">Für Benutzer, die sich im Europäischen Wirtschaftsraum befinden (ausgenommen Deutschland)</span></strong></p>
            <p><strong>Sie befinden sich in einem Mitgliedstaat des Europäischen Wirtschaftsraums („EWR“) oder sind dort ansässig und sind ein „qualifizierter Anleger“ im Sinne von Artikel 2(e) der Verordnung (EU) 2017/1129 des Europäischen Parlaments und des Rates vom 14. Juni 2017 über den Prospekt, der beim öffentlichen Angebot von Wertpapieren oder bei deren Zulassung zum Handel an einem geregelten Markt zu veröffentlichen ist, und zur Aufhebung der Richtlinie 2003/71/EG. Falls Sie als Treuhänder oder Vertreter für eines oder mehrere Anlegerkonten handeln, (a) ist jedes dieser Konten ein qualifizierter Anleger, (b) verfügen Sie über eine Verwaltungsvollmacht für Anlagen für jedes dieser Konten und (c) verfügen Sie über eine uneingeschränkte Befugnis und Ermächtigung, die in dieser Bestätigung enthaltenen Zusicherungen, Verpflichtungen und Anerkenntnisse für jedes dieser Konten abzugeben.</strong></p>
            <p>In bestimmten Rechtsordnungen kann es rechtswidrig sein, die Unterlagen einzusehen, die Sie im Begriff sind abzurufen. In anderen Rechtsordnungen ist es möglicherweise nur bestimmten Personengruppen gestattet, solche Unterlagen einzusehen. Jede Person, die bestrebt ist, diese Unterlagen einzusehen, hat sich zunächst zu vergewissern, dass sie nicht ortsbedingten Anforderungen unterfällt, die ihr dies verbieten oder insofern einschränken.</p>
            <p>Sollte es Ihnen nicht erlaubt sein, die auf diesen Webseiten enthaltenen Unterlagen einzusehen oder bestehen in Ansehung Ihrer Berechtigung insofern irgendwelche Zweifel, verlassen Sie bitte diese Webseite.</p>
            <p><strong>Grundlage des Zugangs</strong></p>
            <p>Der Zugang zu digitalisierten Ausfertigungen dieser Unterlagen wird auf diesen Webseiten von der [COMPANY AG] (die „Gesellschaft“) in gutem Glauben und ausschließlich zu Informationszwecken angeboten. Der Umstand, dass Pressemitteilungen und andere Dokumente in digitalisierter Form auf dieser Webseite zugänglich gemacht werden, stellt kein Angebot und keine Aufforderung dar, ein Angebot gerichtet auf den Erwerb von Aktien der [COMPANY AG] abzugeben. Des Weiteren begründet dies keine Empfehlung der Gesellschaft oder eines Dritten, Aktien an der [COMPANY AG] zu kaufen oder zu verkaufen.</p>
            <p>Sie stimmen zu, dass die Unterlagen, die Sie erhalten, für Ihren eigenen Gebrauch sind und dass Sie diese nicht an andere Personen verteilen werden.</p>
            <p>Soweit Mitteilungen auf dieser Internetseite zukunftsgerichtete Aussagen enthalten, stellen diese keine Tatsachen dar und sind durch die Worte „werden“, „erwarten“, „glauben“, „schätzen“, „beabsichtigen“, „anstreben“, „davon ausgehen“ und ähnliche Wendungen gekennzeichnet. Diese Aussagen bringen Absichten, Ansichten oder gegenwärtige Erwartungen und Annahmen der [COMPANY AG] zum Ausdruck und beruhen auf gegenwärtigen Planungen, Schätzungen und Prognosen, welche die [COMPANY AG] nach bestem Wissen vorgenommen hat. Zukunftsgerichtete Aussagen unterliegen Risiken und Ungewissheiten, die meist nur schwer vorherzusagen sind und gewöhnlich nicht beeinflusst werden können. Es sollte berücksichtigt werden, dass die tatsächlichen Ergebnisse oder Folgen erheblich von den in den zukunftsgerichteten Aussagen angegebenen oder enthaltenen Ereignissen abweichen können.</p>
            <p><strong>Verständnisbestätigung und Annahme des Haftungsausschlusses</strong></p>
            <p>Mit Drücken des “Weiter”-Buttons</p>
            <ul>
				<li>versichern Sie, dass Sie sich nicht in den Vereinigten Staaten (es sei denn, Sie sind ein „Qualified Institutional Buyer“, im Sinne der obigen Definition), Kanada, Australien oder Japan oder einer Rechtsordnung, in welcher der Vertrieb oder die Veröffentlichung rechtswidrig wäre, befinden;</li>
				<li>versichern Sie, sofern Sie sich im Vereinigten Königreich befinden, dass Sie eine „relevante Person“ (im Sinne der obigen Definition) sind; und</li>
				<li>versichern Sie, sofern Sie sich im Europäischen Wirtschaftsraum (ausgenommen Deutschland) befinden, dass Sie ein „qualifizierter Anleger“ (im Sinne der obigen Definition) sind.</li>
            </ul>
            <p>Ich habe den vorstehenden Haftungsausschluss gelesen und verstanden. Mir ist bewusst, dass er meine Rechtsposition beeinflussen kann. Ich erkläre mich mit dessen Bedingungen einverstanden. Indem ich den “Weiter”-Button drücke, bestätige ich, dass ich zu den digitalisierten Fassungen dieser Unterlagen voranschreiten darf.</p>`
		},
		no_access_phase: {
			content: `<p>Aufgrund der anwendbaren rechtlichen Beschränkungen sind elektronische Versionen dieser Materialien für Personen mit Sitz in den von Ihnen angegebenen Rechtsordnungen nicht zugänglich. Bitte klicken Sie <a href="/">hier</a>, um auf die Homepage zurückzukehren.</p>`
		}
	}*/
};
