export const ipo = {
    default: {
        location_validation_phase: {
            heading: `HAFTUNGSAUSSCHLUSS`,
            content: `Aufgrund der anwendbaren rechtlichen Beschränkungen ist der Zugang zu diesem Bereich unserer Website auf Personen beschränkt, die sich in bestimmten Jurisdiktionen aufhalten. Bitte geben Sie Ihren Aufenthaltsort an.`
        },
        disclaimer_consent_phase: {
            heading: `HAFTUNGSAUSSCHLUSS – WICHTIG`,
            content: `<p><strong>Die auf den folgenden Webseiten enthaltenen Unterlagen sind nicht an Personen gerichtet, die sich in den Vereinigten Staaten (es sei denn, sie sind „Qualified Institutional Buyers“ im Sinne des U.S. Securities Act von 1933, in der gültigen Fassung, (der “Securities Act”)), Kanada, Australien oder Japan oder einer Rechtsordnung, in welcher eine Verteilung oder Veröffentlichung rechtswidrig wäre, befinden, oder für deren Zugriff bestimmt. Diese Unterlagen begründen oder bilden weder in den Vereinigten Staaten, Australien, Kanada oder Japan oder einer Rechtsordnung, in welcher ein solches Angebot oder eine solche Werbung nicht gestattet sind, noch gegenüber einer Person, der gegenüber es rechtswidrig ist, ein solches Angebot abzugeben oder eine solche Aufforderung zu schalten, einen Teil eines Angebots oder eine Aufforderung dazu, Wertpapiere zu erwerben oder zu zeichnen.</strong></p>
            <p><strong>Die hier erwähnten Aktien wurden nicht und werden nicht gemäß dem Securities Act registriert werden und dürfen in den Vereinigten Staaten außer im Rahmen der Ausnahmetatbestände von den Registrierungsanforderungen des Securities Act nicht angeboten oder verkauft werden. In den Vereinigten Staaten wird es für die Aktien kein öffentliches Angebot geben.</strong></p>
            <p><strong><span class="text-underline">Für Benutzer, die sich im Vereinigten Königreich befinden</span></strong></p>
            <p><strong>Die nachfolgenden Unterlagen sind innerhalb des Vereinigten Königreiches nur an (i) professionelle Anleger, die unter Artikel 19(5) der Financial Services and Markets Act 2000 (Financial Promotion) Order 2005, in der jeweils gültigen Fassung, (die „Verordnung“) fallen, oder (ii) vermögende Gesellschaften und andere Personen, die unter Artikel 49(2)(a) bis (d) der Verordnung fallen und an die man rechtmäßig herantreten kann, verteilt werden und sind nur an sie gerichtet oder (iii) Personen denen eine Einladung oder Aufforderung zur Ausübung einer Investitionstätigkeit (im Sinne von Abschnitt 21 des Financial Services and Markets Act 2000) im Zusammenhang mit der Ausgabe oder dem Verkauf von Wertpapieren anderweitig rechtmäßig kommuniziert oder die Kommunikation veranlasst werden darf (wobei diese Personen zusammen als „relevante Personen“ bezeichnet werden). Die Aktien stehen nur relevanten Personen zur Verfügung und jede Aufforderung, jedes Angebot oder jede Vereinbarung, solche Aktien zu zeichnen, zu kaufen oder anderweitig zu erwerben, wird nur gegenüber relevanten Personen abgegeben. Personen, die keine relevanten Personen sind, sollten in keinem Fall im Hinblick oder im Vertrauen auf diese Unterlagen oder ihren Inhalt handeln.</strong></p>
            <p><strong><span class="text-underline">Für Benutzer, die sich im Europäischen Wirtschaftsraum befinden (ausgenommen Deutschland)</span></strong></p>
            <p><strong>Sie befinden sich in einem Mitgliedstaat des Europäischen Wirtschaftsraums („EWR“) oder sind dort ansässig und sind ein „qualifizierter Anleger“ im Sinne von Artikel 2(e) der Verordnung (EU) 2017/1129 des Europäischen Parlaments und des Rates vom 14. Juni 2017 über den Prospekt, der beim öffentlichen Angebot von Wertpapieren oder bei deren Zulassung zum Handel an einem geregelten Markt zu veröffentlichen ist, und zur Aufhebung der Richtlinie 2003/71/EG. Falls Sie als Treuhänder oder Vertreter für eines oder mehrere Anlegerkonten handeln, (a) ist jedes dieser Konten ein qualifizierter Anleger, (b) verfügen Sie über eine Verwaltungsvollmacht für Anlagen für jedes dieser Konten und (c) verfügen Sie über eine uneingeschränkte Befugnis und Ermächtigung, die in dieser Bestätigung enthaltenen Zusicherungen, Verpflichtungen und Anerkenntnisse für jedes dieser Konten abzugeben.</strong></p>
            <p>In bestimmten Rechtsordnungen kann es rechtswidrig sein, die Unterlagen einzusehen, die Sie im Begriff sind abzurufen. In anderen Rechtsordnungen ist es möglicherweise nur bestimmten Personengruppen gestattet, solche Unterlagen einzusehen. Jede Person, die bestrebt ist, diese Unterlagen einzusehen, hat sich zunächst zu vergewissern, dass sie nicht ortsbedingten Anforderungen unterfällt, die ihr dies verbieten oder insofern einschränken.</p>
            <p>Sollte es Ihnen nicht erlaubt sein, die auf diesen Webseiten enthaltenen Unterlagen einzusehen oder bestehen in Ansehung Ihrer Berechtigung insofern irgendwelche Zweifel, verlassen Sie bitte diese Webseite.</p>
            <p><strong>Grundlage des Zugangs</strong></p>
            <p>Der Zugang zu digitalisierten Ausfertigungen dieser Unterlagen wird auf diesen Webseiten von der [COMPANY AG] (die „Gesellschaft“) in gutem Glauben und ausschließlich zu Informationszwecken angeboten. Der Umstand, dass Pressemitteilungen und andere Dokumente in digitalisierter Form auf dieser Webseite zugänglich gemacht werden, stellt kein Angebot und keine Aufforderung dar, ein Angebot gerichtet auf den Erwerb von Aktien der [COMPANY AG] abzugeben. Des Weiteren begründet dies keine Empfehlung der Gesellschaft oder eines Dritten, Aktien an der [COMPANY AG] zu kaufen oder zu verkaufen.</p>
            <p>Sie stimmen zu, dass die Unterlagen, die Sie erhalten, für Ihren eigenen Gebrauch sind und dass Sie diese nicht an andere Personen verteilen werden.</p>
            <p>Soweit Mitteilungen auf dieser Internetseite zukunftsgerichtete Aussagen enthalten, stellen diese keine Tatsachen dar und sind durch die Worte „werden“, „erwarten“, „glauben“, „schätzen“, „beabsichtigen“, „anstreben“, „davon ausgehen“ und ähnliche Wendungen gekennzeichnet. Diese Aussagen bringen Absichten, Ansichten oder gegenwärtige Erwartungen und Annahmen der [COMPANY AG] zum Ausdruck und beruhen auf gegenwärtigen Planungen, Schätzungen und Prognosen, welche die [COMPANY AG] nach bestem Wissen vorgenommen hat. Zukunftsgerichtete Aussagen unterliegen Risiken und Ungewissheiten, die meist nur schwer vorherzusagen sind und gewöhnlich nicht beeinflusst werden können. Es sollte berücksichtigt werden, dass die tatsächlichen Ergebnisse oder Folgen erheblich von den in den zukunftsgerichteten Aussagen angegebenen oder enthaltenen Ereignissen abweichen können.</p>
            <p><strong>Verständnisbestätigung und Annahme des Haftungsausschlusses</strong></p>
            <p>Mit Drücken des “Weiter”-Buttons</p>
            <ul>
				<li>versichern Sie, dass Sie sich nicht in den Vereinigten Staaten (es sei denn, Sie sind ein „Qualified Institutional Buyer“, im Sinne der obigen Definition), Kanada, Australien oder Japan oder einer Rechtsordnung, in welcher der Vertrieb oder die Veröffentlichung rechtswidrig wäre, befinden;</li>
				<li>versichern Sie, sofern Sie sich im Vereinigten Königreich befinden, dass Sie eine „relevante Person“ (im Sinne der obigen Definition) sind; und</li>
				<li>versichern Sie, sofern Sie sich im Europäischen Wirtschaftsraum (ausgenommen Deutschland) befinden, dass Sie ein „qualifizierter Anleger“ (im Sinne der obigen Definition) sind.</li>
            </ul>
            <p>Ich habe den vorstehenden Haftungsausschluss gelesen und verstanden. Mir ist bewusst, dass er meine Rechtsposition beeinflussen kann. Ich erkläre mich mit dessen Bedingungen einverstanden. Indem ich den “Weiter”-Button drücke, bestätige ich, dass ich zu den digitalisierten Fassungen dieser Unterlagen voranschreiten darf.</p>`
        },
        no_access_phase: {
            content: `<p>Aufgrund der anwendbaren rechtlichen Beschränkungen sind elektronische Versionen dieser Materialien für Personen mit Sitz in den von Ihnen angegebenen Rechtsordnungen nicht zugänglich. Bitte klicken Sie <a href="/">hier</a>, um auf die Homepage zurückzukehren.</p>`
        }
    }
};
